[project]
name = "dspy-reproduction-repo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = ["dspy>=2.6.23", "mlflow>=2.22.0", "ipykernel>=6.29.5"]
